# Config file for CelebA dataset (200k)

output_dir: './output'
structure: 'linear'
device_id: ('0')
dataset:
  img_dir: '/home/jechterh/teams/group-9/nih_data/train'
  folder: False
  resolution: 128
sched:
  epochs: [8,16,16,16,16,12]
